# Generated by Django 4.1.5 on 2023-01-25 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stacks", "0001_initial"),
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=50)),
                ("obs", models.TextField(max_length=50)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Pleno", "Pleno"),
                            ("Senior", "Senior"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "develop",
                    models.CharField(
                        choices=[
                            ("Front-end", "Front End"),
                            ("Back-end", "Back End"),
                            ("Full-stack", "Full Stack"),
                        ],
                        max_length=50,
                    ),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                (
                    "stacks",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="stacks.stack"
                    ),
                ),
                (
                    "status",
                    models.ManyToManyField(
                        blank=True, related_name="applications", to="status.status"
                    ),
                ),
            ],
        ),
    ]
