# Generated by Django 4.1.5 on 2023-01-25 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Analise de CV", "Cv"),
                            ("Teste Fit Cultural", "Fit"),
                            ("Teste Técnico", "Teste"),
                            ("Entrevista RH", "Rh"),
                            ("Entrevista Técnica", "Tecnico"),
                            ("Contratado", "Contratado"),
                            ("Recusado", "Recusado"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
